/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import farmpowerDB.ConectaBD;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import farmpowerDB.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Psnps
 */
public class cadastroPedidos extends javax.swing.JFrame {
    ConectaBD conecta = new ConectaBD();

    /**
     * Creates new form cadastroPedidos
     */
    public cadastroPedidos() {
        initComponents();
        conecta.conexao();
        preencherTabela("select * from pedidos order by id_pedidos");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JTextField();
        txtPedidoUrgencia = new javax.swing.JTextField();
        txtPedidoMedicamento = new javax.swing.JTextField();
        txtPedidoQuantidade = new javax.swing.JTextField();
        btnAdicionarPedido = new javax.swing.JButton();
        btnAlterarPedidos = new javax.swing.JButton();
        btnExcluirPedido = new javax.swing.JButton();
        btnSairEstoque = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPedidoId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSalvarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnPrimeiroEstoque = new javax.swing.JButton();
        btnUltimoEstoque = new javax.swing.JButton();
        btnSeguinteEstoque = new javax.swing.JButton();
        btnAnteriorEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Medicamento:");

        jLabel3.setText("Data:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Urgência:");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 24)); // NOI18N
        jLabel1.setText("Pedidos de medicamentos");

        txtDataPedido.setEnabled(false);

        txtPedidoUrgencia.setEnabled(false);

        txtPedidoMedicamento.setEnabled(false);
        txtPedidoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPedidoMedicamentoActionPerformed(evt);
            }
        });

        txtPedidoQuantidade.setEnabled(false);

        btnAdicionarPedido.setText("Adicionar");
        btnAdicionarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPedidoActionPerformed(evt);
            }
        });

        btnAlterarPedidos.setText("Alterar");
        btnAlterarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPedidosActionPerformed(evt);
            }
        });

        btnExcluirPedido.setText("Excluir");
        btnExcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPedidoActionPerformed(evt);
            }
        });

        btnSairEstoque.setText("Sair");
        btnSairEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEstoqueActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Descrição urgência do pedido:");

        jLabel7.setText("Tipo 1:");

        jLabel10.setText("Maxíma");

        jLabel8.setText("Tipo 2:");

        jLabel11.setText("Mediana");

        jLabel9.setText("Tipo 3:");

        jLabel12.setText("Mínima");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtPedidoId.setEnabled(false);

        jLabel13.setText("ID: ");

        btnSalvarPedido.setText("Salvar");
        btnSalvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdicionarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterarPedidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluirPedido)
                                .addGap(71, 71, 71)
                                .addComponent(btnSairEstoque))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPedidoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPedidoQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(txtDataPedido)
                                    .addComponent(txtPedidoUrgencia))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPedidoId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPedidoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPedidoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPedidoUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPedidoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirPedido)
                    .addComponent(btnAlterarPedidos)
                    .addComponent(btnSalvarPedido)
                    .addComponent(btnAdicionarPedido)
                    .addComponent(btnSairEstoque))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPedidos);

        btnPrimeiroEstoque.setText("Primeiro");
        btnPrimeiroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroEstoqueActionPerformed(evt);
            }
        });

        btnUltimoEstoque.setText("Ultimo");
        btnUltimoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoEstoqueActionPerformed(evt);
            }
        });

        btnSeguinteEstoque.setText("Seguinte");
        btnSeguinteEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguinteEstoqueActionPerformed(evt);
            }
        });

        btnAnteriorEstoque.setText("Anterior");
        btnAnteriorEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnPrimeiroEstoque)
                .addGap(18, 18, 18)
                .addComponent(btnSeguinteEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnteriorEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUltimoEstoque)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiroEstoque)
                    .addComponent(btnSeguinteEstoque)
                    .addComponent(btnAnteriorEstoque)
                    .addComponent(btnUltimoEstoque))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(646, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPedidoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPedidoMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedidoMedicamentoActionPerformed

    private void btnAdicionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPedidoActionPerformed
        // TODO add your handling code here:
        txtPedidoMedicamento.setText("");
        txtPedidoQuantidade.setText("");
        txtDataPedido.setText("");
        txtPedidoUrgencia.setText("");
        txtPedidoId.setText("");
        txtPedidoMedicamento.setEnabled(true);
        txtPedidoQuantidade.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtPedidoUrgencia.setEnabled(true);
        btnAlterarPedidos.setEnabled(true);
        btnExcluirPedido.setEnabled(true);
    }//GEN-LAST:event_btnAdicionarPedidoActionPerformed

    private void btnAlterarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPedidosActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("update pedidos set nome_pedido=?, qtd_pedido=?, data_pedido=?,urgencia_pedido=? where id_pedidos=?");
            pst.setString(1, txtPedidoMedicamento.getText());
            pst.setString(2, txtPedidoQuantidade.getText());
            pst.setString(3, txtDataPedido.getText());
            pst.setString(4, txtPedidoUrgencia.getText());
            pst.setInt(5, Integer.parseInt(txtPedidoId.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
            preencherTabela("select * from  pedidos order by id_pedidos");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao alterar!!\n ERRO: "+ex);
        }
        txtPedidoMedicamento.setText("");
        txtPedidoQuantidade.setText("");
        txtDataPedido.setText("");
        txtPedidoUrgencia.setText("");
        txtPedidoId.setText("");
        txtPedidoMedicamento.setEnabled(true);
        txtPedidoQuantidade.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtPedidoUrgencia.setEnabled(true);
        btnAlterarPedidos.setEnabled(false);
        btnExcluirPedido.setEnabled(false);
    }//GEN-LAST:event_btnAlterarPedidosActionPerformed

    private void btnSalvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPedidoActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("insert into pedidos(nome_pedido, qtd_pedido, data_pedido, urgencia_pedido)values(?,?,?,?)");
            pst.setString(1, txtPedidoMedicamento.getText());
            pst.setString(2, txtPedidoQuantidade.getText());
            pst.setString(3, txtDataPedido.getText());
            pst.setString(4, txtPedidoUrgencia.getText());
            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
            pst.executeUpdate();
            preencherTabela("select * from pedidos order by id_pedidos");
           
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO FILHO ERRO!!\n ERRO: "+ex);
        }
        txtPedidoMedicamento.setText("");
        txtPedidoQuantidade.setText("");
        txtDataPedido.setText("");
        txtPedidoUrgencia.setText("");
        txtPedidoId.setText("");
        txtPedidoMedicamento.setEnabled(false);
        txtPedidoQuantidade.setEnabled(false);
        txtDataPedido.setEnabled(false);
        txtPedidoUrgencia.setEnabled(false);
        btnAlterarPedidos.setEnabled(false);
        btnExcluirPedido.setEnabled(false);
        btnAdicionarPedido.setEnabled(true);
    }//GEN-LAST:event_btnSalvarPedidoActionPerformed

    private void btnExcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPedidoActionPerformed
        // TODO add your handling code here:
        conecta.executaSQL("delete from pedidos where nome_pedido='"+txtPedidoMedicamento.getText()+"'");
        JOptionPane.showMessageDialog(rootPane, "Cadastro Deletado com sucesso!!");
        preencherTabela("select * from  pedidos order by id_pedidos");
        txtPedidoMedicamento.setText("");
        txtPedidoQuantidade.setText("");
        txtDataPedido.setText("");
        txtPedidoUrgencia.setText("");
        txtPedidoId.setText("");
        
    }//GEN-LAST:event_btnExcluirPedidoActionPerformed

    private void btnPrimeiroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroEstoqueActionPerformed
        // TODO add your handling code here:
        txtPedidoMedicamento.setEnabled(true);
        txtPedidoQuantidade.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtPedidoUrgencia.setEnabled(true);
        btnAlterarPedidos.setEnabled(true);
        btnExcluirPedido.setEnabled(true);
        try {
            conecta.executaSQL("select * from pedidos");
            conecta.rs.first();
            
            txtPedidoId.setText(String.valueOf(conecta.rs.getInt("id_pedidos")));
            txtPedidoMedicamento.setText(conecta.rs.getString("nome_pedido"));
            txtPedidoQuantidade.setText(conecta.rs.getString("qtd_pedido"));
            txtDataPedido.setText(conecta.rs.getString("data_pedido"));
            txtPedidoUrgencia.setText(conecta.rs.getString("urgencia_pedido"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnPrimeiroEstoqueActionPerformed

    private void btnSeguinteEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguinteEstoqueActionPerformed
        // TODO add your handling code here:
        txtPedidoMedicamento.setEnabled(true);
        txtPedidoQuantidade.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtPedidoUrgencia.setEnabled(true);
        btnAlterarPedidos.setEnabled(true);
        btnExcluirPedido.setEnabled(true);
        try {
            
            conecta.rs.next();
            
            txtPedidoId.setText(String.valueOf(conecta.rs.getInt("id_pedidos")));
            txtPedidoMedicamento.setText(conecta.rs.getString("nome_pedido"));
            txtPedidoQuantidade.setText(conecta.rs.getString("qtd_pedido"));
            txtDataPedido.setText(conecta.rs.getString("data_pedido"));
            txtPedidoUrgencia.setText(conecta.rs.getString("urgencia_pedido"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnSeguinteEstoqueActionPerformed

    private void btnAnteriorEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorEstoqueActionPerformed
        // TODO add your handling code here:
        txtPedidoMedicamento.setEnabled(true);
        txtPedidoQuantidade.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtPedidoUrgencia.setEnabled(true);
        btnAlterarPedidos.setEnabled(true);
        btnExcluirPedido.setEnabled(true);
        try {
            
            conecta.rs.previous();
            
            txtPedidoId.setText(String.valueOf(conecta.rs.getInt("id_pedidos")));
            txtPedidoMedicamento.setText(conecta.rs.getString("nome_pedido"));
            txtPedidoQuantidade.setText(conecta.rs.getString("qtd_pedido"));
            txtDataPedido.setText(conecta.rs.getString("data_pedido"));
            txtPedidoUrgencia.setText(conecta.rs.getString("urgencia_pedido"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados ANTERIOR!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnAnteriorEstoqueActionPerformed

    private void btnUltimoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoEstoqueActionPerformed
        // TODO add your handling code here:
        txtPedidoMedicamento.setEnabled(true);
        txtPedidoQuantidade.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtPedidoUrgencia.setEnabled(true);
        btnAlterarPedidos.setEnabled(true);
        btnExcluirPedido.setEnabled(true);
        try {
            conecta.executaSQL("select * from pedidos");
            conecta.rs.last();
            
            txtPedidoId.setText(String.valueOf(conecta.rs.getInt("id_pedidos")));
            txtPedidoMedicamento.setText(conecta.rs.getString("nome_pedido"));
            txtPedidoQuantidade.setText(conecta.rs.getString("qtd_pedido"));
            txtDataPedido.setText(conecta.rs.getString("data_pedido"));
            txtPedidoUrgencia.setText(conecta.rs.getString("urgencia_pedido"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnUltimoEstoqueActionPerformed

    private void btnSairEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEstoqueActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairEstoqueActionPerformed
    
    
    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"ID","Nome","Data","Quantidade","Urgência"};
        
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            
            do {                
                dados.add(new Object[]{conecta.rs.getInt("id_pedidos"),conecta.rs.getString("nome_pedido"),conecta.rs.getString("data_pedido"),conecta.rs.getString("qtd_pedido"),conecta.rs.getString("urgencia_pedido")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o array!!\n ERRO: "+ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tblPedidos.setModel(modelo);
        tblPedidos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblPedidos.getColumnModel().getColumn(0).setResizable(false);
        tblPedidos.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblPedidos.getColumnModel().getColumn(1).setResizable(false);
        tblPedidos.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblPedidos.getColumnModel().getColumn(2).setResizable(false);
        tblPedidos.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblPedidos.getColumnModel().getColumn(3).setResizable(false);
        tblPedidos.getTableHeader().setReorderingAllowed(false);
        tblPedidos.setAutoResizeMode(tblPedidos.AUTO_RESIZE_OFF);
        tblPedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPedido;
    private javax.swing.JButton btnAlterarPedidos;
    private javax.swing.JButton btnAnteriorEstoque;
    private javax.swing.JButton btnExcluirPedido;
    private javax.swing.JButton btnPrimeiroEstoque;
    private javax.swing.JButton btnSairEstoque;
    private javax.swing.JButton btnSalvarPedido;
    private javax.swing.JButton btnSeguinteEstoque;
    private javax.swing.JButton btnUltimoEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtPedidoId;
    private javax.swing.JTextField txtPedidoMedicamento;
    private javax.swing.JTextField txtPedidoQuantidade;
    private javax.swing.JTextField txtPedidoUrgencia;
    // End of variables declaration//GEN-END:variables
}
