/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import farmpowerDB.ConectaBD;
import farmpowerDB.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Psnps
 */
public class cadastroFornecedores extends javax.swing.JFrame {
     ConectaBD conecta = new ConectaBD();

    /**
     * Creates new form cadastroFornecedores
     */
    public cadastroFornecedores() {
        initComponents();
        conecta.conexao();
        preencherTabela("select * from  fornecedores order by id_fornecedores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CadastroFornecedores = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        txtFornecedorEstado = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        btnCadastrarFornecedor = new javax.swing.JButton();
        btnAlterarFornecedor = new javax.swing.JButton();
        btnSalvarFornecedor = new javax.swing.JButton();
        btnExcluirFornecedor = new javax.swing.JButton();
        btnExitFornecedores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdFornecedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        btnPrimeiroFornecedores = new javax.swing.JButton();
        btnUltimoFornecedores = new javax.swing.JButton();
        btnProximoFornecedores = new javax.swing.JButton();
        btnAnteriorFornecedores = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel2.setText("Cadastro de Fornecedores");

        jLabel3.setText("Fornecedor:");

        jLabel4.setText("Estado:");

        jLabel5.setText("CNPJ:");

        txtFornecedor.setEnabled(false);
        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });

        txtFornecedorEstado.setEnabled(false);

        txtCNPJ.setEnabled(false);
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });

        btnCadastrarFornecedor.setText("Novo");
        btnCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFornecedorActionPerformed(evt);
            }
        });

        btnAlterarFornecedor.setText("Alterar");
        btnAlterarFornecedor.setEnabled(false);
        btnAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFornecedorActionPerformed(evt);
            }
        });

        btnSalvarFornecedor.setText("Salvar");
        btnSalvarFornecedor.setEnabled(false);
        btnSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFornecedorActionPerformed(evt);
            }
        });

        btnExcluirFornecedor.setText("Excluir");
        btnExcluirFornecedor.setEnabled(false);
        btnExcluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFornecedorActionPerformed(evt);
            }
        });

        btnExitFornecedores.setText("Exit");
        btnExitFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitFornecedoresActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        txtIdFornecedor.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFornecedorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(71, 71, 71)))))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCadastrarFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitFornecedores)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFornecedorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarFornecedor)
                    .addComponent(btnAlterarFornecedor)
                    .addComponent(btnSalvarFornecedor)
                    .addComponent(btnExcluirFornecedor)
                    .addComponent(btnExitFornecedores))
                .addContainerGap())
        );

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblFornecedores);

        btnPrimeiroFornecedores.setText("Primeiro");
        btnPrimeiroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroFornecedoresActionPerformed(evt);
            }
        });

        btnUltimoFornecedores.setText("Ultimo");
        btnUltimoFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoFornecedoresActionPerformed(evt);
            }
        });

        btnProximoFornecedores.setText("Proximo");
        btnProximoFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoFornecedoresActionPerformed(evt);
            }
        });

        btnAnteriorFornecedores.setText("Anterior");
        btnAnteriorFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroFornecedoresLayout = new javax.swing.GroupLayout(CadastroFornecedores);
        CadastroFornecedores.setLayout(CadastroFornecedoresLayout);
        CadastroFornecedoresLayout.setHorizontalGroup(
            CadastroFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroFornecedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(CadastroFornecedoresLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnPrimeiroFornecedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUltimoFornecedores)
                .addGap(79, 79, 79)
                .addComponent(btnProximoFornecedores)
                .addGap(70, 70, 70)
                .addComponent(btnAnteriorFornecedores)
                .addGap(76, 76, 76))
        );
        CadastroFornecedoresLayout.setVerticalGroup(
            CadastroFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroFornecedoresLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUltimoFornecedores)
                    .addComponent(btnProximoFornecedores)
                    .addComponent(btnAnteriorFornecedores)
                    .addComponent(btnPrimeiroFornecedores))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CadastroFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(CadastroFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(669, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void btnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        preencherTabela("select * from  fornecedores order by id_fornecedores");
        txtFornecedor.setText("");
        txtFornecedorEstado.setText("");
        txtCNPJ.setText("");
        txtFornecedor.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtFornecedorEstado.setEnabled(true);
        btnCadastrarFornecedor.setEnabled(false);
        btnAlterarFornecedor.setEnabled(true);
        btnSalvarFornecedor.setEnabled(true);
        btnExcluirFornecedor.setEnabled(true);
    }//GEN-LAST:event_btnCadastrarFornecedorActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void btnSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFornecedorActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("insert into fornecedores(nome_fornecedores,cnpj_fornecedores,estado_fornecedores)values(?,?,?)");
            pst.setString(1, txtFornecedor.getText());
            pst.setString(2,txtFornecedorEstado.getText());
            pst.setString(3, txtCNPJ.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Fornecedor Salvo com sucesso!");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro na inserção!!\n ERRO:  "+ex);
        }
        preencherTabela("select * from  fornecedores order by id_fornecedores");
        txtFornecedor.setText("");
        txtFornecedorEstado.setText("");
        txtCNPJ.setText("");
        txtFornecedor.setEnabled(false);
        txtFornecedorEstado.setEnabled(false);
        txtCNPJ.setEnabled(false);
        btnSalvarFornecedor.setEnabled(false);
        btnAlterarFornecedor.setEnabled(false);
        btnExcluirFornecedor.setEnabled(false);
        btnCadastrarFornecedor.setEnabled(true);
    }//GEN-LAST:event_btnSalvarFornecedorActionPerformed

    private void btnExitFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitFornecedoresActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitFornecedoresActionPerformed

    private void btnExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFornecedorActionPerformed
        // TODO add your handling code here:
        conecta.executaSQL("delete from fornecedores where cnpj_fornecedores='"+txtCNPJ.getText()+"'");
        JOptionPane.showMessageDialog(rootPane, "Fornecedor Deletado com sucesso!!");
        preencherTabela("select * from  fornecedores order by id_fornecedores");
        txtFornecedor.setText("");
        txtFornecedorEstado.setText("");
        txtCNPJ.setText("");
        txtFornecedor.setEnabled(false);
        txtFornecedorEstado.setEnabled(false);
        txtCNPJ.setEnabled(false);
        btnSalvarFornecedor.setEnabled(false);
        btnAlterarFornecedor.setEnabled(false);
        btnExcluirFornecedor.setEnabled(false);
        btnCadastrarFornecedor.setEnabled(true);
    }//GEN-LAST:event_btnExcluirFornecedorActionPerformed

    private void btnAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFornecedorActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("update fornecedores set nome_fornecedores=?, estado_fornecedores=?, cnpj_fornecedores=? where id_fornecedores=?");
            pst.setString(1, txtFornecedor.getText());
            pst.setString(2, txtFornecedorEstado.getText());
            pst.setString(3, txtCNPJ.getText());
            pst.setInt(4, Integer.parseInt(txtIdFornecedor.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
            preencherTabela("select * from fornecedores order by id_fornecedores");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao alterar!!\n ERRO: "+ex);
        }
        txtFornecedor.setText("");
        txtFornecedorEstado.setText("");
        txtCNPJ.setText("");
        txtIdFornecedor.setText("");
    }//GEN-LAST:event_btnAlterarFornecedorActionPerformed

    private void btnUltimoFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoFornecedoresActionPerformed
        // TODO add your handling code here:
        txtFornecedor.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtFornecedorEstado.setEnabled(true);
        btnAlterarFornecedor.setEnabled(true);
        btnExcluirFornecedor.setEnabled(true);
        try {
            conecta.executaSQL("select * from fornecedores");
            conecta.rs.last();
            txtFornecedor.setText(conecta.rs.getString("nome_fornecedores"));
            txtFornecedorEstado.setText(conecta.rs.getString("estado_fornecedores"));
            txtCNPJ.setText(conecta.rs.getString("cnpj_fornecedores"));
            txtIdFornecedor.setText(String.valueOf(conecta.rs.getInt("id_fornecedores")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnUltimoFornecedoresActionPerformed

    private void btnPrimeiroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroFornecedoresActionPerformed
        // TODO add your handling code here:
        txtFornecedor.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtFornecedorEstado.setEnabled(true);
        btnAlterarFornecedor.setEnabled(true);
        btnExcluirFornecedor.setEnabled(true);
        
        try {
            conecta.executaSQL("select * from fornecedores");
            conecta.rs.first();
            txtFornecedor.setText(conecta.rs.getString("nome_fornecedores"));
            txtFornecedorEstado.setText(conecta.rs.getString("estado_fornecedores"));
            txtCNPJ.setText(conecta.rs.getString("cnpj_fornecedores"));
            txtIdFornecedor.setText(String.valueOf(conecta.rs.getInt("id_fornecedores")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnPrimeiroFornecedoresActionPerformed

    private void btnProximoFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoFornecedoresActionPerformed
        // TODO add your handling code here:
        txtFornecedor.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtFornecedorEstado.setEnabled(true);
        btnAlterarFornecedor.setEnabled(true);
        btnExcluirFornecedor.setEnabled(true);
        try {
            // TODO add your handling code here:
            conecta.rs.next();
            txtFornecedor.setText(conecta.rs.getString("nome_fornecedores"));
            txtFornecedorEstado.setText(conecta.rs.getString("estado_fornecedores"));
            txtCNPJ.setText(conecta.rs.getString("cnpj_fornecedores"));
            txtIdFornecedor.setText(String.valueOf(conecta.rs.getInt("id_fornecedores")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnProximoFornecedoresActionPerformed

    private void btnAnteriorFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorFornecedoresActionPerformed
        // TODO add your handling code here:
        txtFornecedor.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtFornecedorEstado.setEnabled(true);
        btnAlterarFornecedor.setEnabled(true);
        btnExcluirFornecedor.setEnabled(true);
        try {
            // TODO add your handling code here:
            conecta.rs.previous();
            txtFornecedor.setText(conecta.rs.getString("nome_fornecedores"));
            txtFornecedorEstado.setText(conecta.rs.getString("estado_fornecedores"));
            txtCNPJ.setText(conecta.rs.getString("cnpj_fornecedores"));
            txtIdFornecedor.setText(String.valueOf(conecta.rs.getInt("id_fornecedores")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar dados!!\n ERRO: "+ex);
        }
    }//GEN-LAST:event_btnAnteriorFornecedoresActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"ID","Nome","Estado","CNPJ"};
        
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {            
                dados.add(new Object[]{conecta.rs.getInt("id_fornecedores"),conecta.rs.getString("nome_fornecedores"),conecta.rs.getString("estado_fornecedores"),conecta.rs.getString("cnpj_fornecedores")});
        } while (conecta.rs.next());
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o array!!\n ERRO: "+ex);
        }
        
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tblFornecedores.setModel(modelo);
        tblFornecedores.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(0).setResizable(false);
        tblFornecedores.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblFornecedores.getColumnModel().getColumn(1).setResizable(false);
        tblFornecedores.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblFornecedores.getColumnModel().getColumn(2).setResizable(false);
        tblFornecedores.getColumnModel().getColumn(3).setPreferredWidth(252);
        tblFornecedores.getColumnModel().getColumn(3).setResizable(false);
        tblFornecedores.getTableHeader().setReorderingAllowed(false);
        tblFornecedores.setAutoResizeMode(tblFornecedores.AUTO_RESIZE_OFF);
        tblFornecedores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
       
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroFornecedores;
    private javax.swing.JButton btnAlterarFornecedor;
    private javax.swing.JButton btnAnteriorFornecedores;
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JButton btnExcluirFornecedor;
    private javax.swing.JButton btnExitFornecedores;
    private javax.swing.JButton btnPrimeiroFornecedores;
    private javax.swing.JButton btnProximoFornecedores;
    private javax.swing.JButton btnSalvarFornecedor;
    private javax.swing.JButton btnUltimoFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtFornecedorEstado;
    private javax.swing.JTextField txtIdFornecedor;
    // End of variables declaration//GEN-END:variables
}
