/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import farmpowerDB.ConectaBD;
import farmpowerDB.ControleVenda;
import farmpowerDB.ModeloTabela;
import farmpowerDB.ModeloVenda;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Psnps
 */
public class menuView extends javax.swing.JFrame {
    ConectaBD conecta = new ConectaBD();
    ModeloVenda mod = new ModeloVenda();
    ControleVenda control = new ControleVenda();
    int flag=1,codVenda;
    float preco_produto,total=0;

    /**
     * Creates new form menuView
     */
    public menuView() {
        initComponents();
        
        
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            txtDataVenda.setFormatterFactory(new DefaultFormatterFactory(form));
            

        } catch (ParseException ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeClienteVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JFormattedTextField();
        btnBuscaCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtProdutoVenda = new javax.swing.JTextField();
        btnBuscaProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorItemVenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValorVendaTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnCancelaVenda = new javax.swing.JButton();
        btnAddProduto = new javax.swing.JButton();
        btnMenuClientes = new javax.swing.JButton();
        btnMenuFornecedores = new javax.swing.JButton();
        btnMenuEstoque = new javax.swing.JButton();
        btnMenuPedidos = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        jLabel3.setText("FORMULÁRIO DE VENDAS");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome: ");

        txtNomeClienteVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("data:");

        txtDataVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataVendaFocusGained(evt);
            }
        });
        txtDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataVendaActionPerformed(evt);
            }
        });

        btnBuscaCliente.setText("Buscar");
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Produto:");

        btnBuscaProduto.setText("Busca");
        btnBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaProdutoActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade:");

        txtQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtdFocusGained(evt);
            }
        });
        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor p/ item: ");

        jLabel7.setText("Valor Total: ");

        txtValorVendaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorVendaTotalActionPerformed(evt);
            }
        });

        tblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisa);

        jLabel8.setText("Tabela de Pesquisa:");

        jLabel9.setText("Itens da Venda: ");

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblItems);

        jButton1.setText("Finalizar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelaVenda.setText("Cancelar Venda");
        btnCancelaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaVendaActionPerformed(evt);
            }
        });

        btnAddProduto.setText("Adicionar Produto");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNomeClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaCliente))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaProduto)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtd)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addGap(0, 49, Short.MAX_VALUE)))
                                .addGap(256, 256, 256))
                            .addComponent(txtValorItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(btnCancelaVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtValorVendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddProduto)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaProduto)
                    .addComponent(txtValorItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(btnAddProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorVendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnCancelaVenda))
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnMenuClientes.setText("Clientes");
        btnMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuClientesActionPerformed(evt);
            }
        });

        btnMenuFornecedores.setText("Fornecedores");
        btnMenuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuFornecedoresActionPerformed(evt);
            }
        });

        btnMenuEstoque.setText("Estoque");
        btnMenuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEstoqueActionPerformed(evt);
            }
        });

        btnMenuPedidos.setText("Pedidos");
        btnMenuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPedidosActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuClientes)
                .addGap(18, 18, 18)
                .addComponent(btnMenuFornecedores)
                .addGap(18, 18, 18)
                .addComponent(btnMenuEstoque)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuEstoque)
                    .addComponent(btnMenuFornecedores)
                    .addComponent(jButton4)
                    .addComponent(btnMenuClientes)
                    .addComponent(btnMenuPedidos))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(725, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        System.exit(0);
        conecta.desconecta();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuClientesActionPerformed
        cadastroCliente cliente = new cadastroCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnMenuClientesActionPerformed

    private void btnMenuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuFornecedoresActionPerformed
        // TODO add your handling code here:
        cadastroFornecedores fornecedores = new cadastroFornecedores();
        fornecedores.setVisible(true);
    }//GEN-LAST:event_btnMenuFornecedoresActionPerformed

    private void btnMenuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEstoqueActionPerformed
        // TODO add your handling code here:
            cadastroEstoque estoque = new cadastroEstoque();
            estoque.setVisible(true);
    }//GEN-LAST:event_btnMenuEstoqueActionPerformed

    private void txtValorVendaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVendaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVendaTotalActionPerformed

    private void btnMenuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPedidosActionPerformed
        // TODO add your handling code here:
        cadastroPedidos pedidos = new cadastroPedidos();
        pedidos.setVisible(true);
    }//GEN-LAST:event_btnMenuPedidosActionPerformed

    private void txtDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataVendaActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
        // TODO add your handling code here:
        conecta.conexao();
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("insert into vendas (valor_venda)values(?)");
            pst.setFloat(1, 0);
            pst.execute();
            conecta.executaSQL("select * from vendas");
            conecta.rs.last();
            codVenda = conecta.rs.getInt("id_vendas");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "ERRO:"+ex);
        }
        flag = 1;
        preencherTabelaCliente("select * from clientes where nome_clientes like '%"+txtNomeClienteVenda.getText()+"%'");
        
    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void txtNomeClienteVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteVendaActionPerformed

    private void btnBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProdutoActionPerformed
        // TODO add your handling code here:
        
        flag = 2;
        preencherTabelaProduto("select * from produtos where nome_produtos like '%"+txtProdutoVenda.getText()+"%'");
        
    }//GEN-LAST:event_btnBuscaProdutoActionPerformed

    private void tblPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaMouseClicked
        // TODO add your handling code here:
        if(flag==1){
            String nome_clientes = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),1);
            txtNomeClienteVenda.setText(nome_clientes);
        }else {
            conecta.conexao();
            try {
                String nome_produtos = "" + tblPesquisa.getValueAt(tblPesquisa.getSelectedRow(),1);
                conecta.executaSQL("select * from produtos where nome_produtos='"+nome_produtos+"'");
                conecta.rs.first();
                preco_produto=conecta.rs.getFloat("preco_produtos");
                txtProdutoVenda.setText(nome_produtos);
                txtValorItemVenda.setText(String.valueOf(preco_produto));
                txtQtd.setText("1");
                conecta.desconecta();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar preço!!\n\n"+ex);
            }
            
        }
    }//GEN-LAST:event_tblPesquisaMouseClicked

    private void txtQtdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdFocusGained
        // TODO add your handling code here:
        //float valorTotal;
        //valorTotal = Float.parseFloat(txtValorItemVenda.getText())*Integer.parseInt(txtQtd.getText());
        //txtValorVendaTotal.setText(String.valueOf(valorTotal));
    }//GEN-LAST:event_txtQtdFocusGained

    private void txtDataVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataVendaFocusGained
        // TODO add your handling code here:
        //float valorTotal;
        //valorTotal = Float.parseFloat(txtValorItemVenda.getText())*Integer.parseInt(txtQtd.getText());
        //txtValorVendaTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtDataVendaFocusGained

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        // TODO add your handling code here:
        int idVenda;
        
        mod.setNomeProduto(txtProdutoVenda.getText());
        mod.setQtdItem(Integer.parseInt(txtQtd.getText()));
        mod.setIdVenda(codVenda);
        control.adicionaItem(mod);
        //total = total+Float.parseFloat(txtValorItemVenda.getText())*Integer.parseInt(txtQtd.getText());
        //txtValorVendaTotal.setText(String.valueOf(total));
        preencherTabelaItens("select * from produtos inner join itens_venda_produtos on produtos.id_produtos = itens_venda_produtos.id_produtos inner join vendas on vendas.id_vendas=itens_venda_produtos.id_vendas where vendas.id_vendas="+codVenda);
        
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaVendaActionPerformed
        // TODO add your handling code here:
        txtNomeClienteVenda.setText("");
        txtProdutoVenda.setText("");
        txtValorItemVenda.setText("");
        txtQtd.setText("");
    }//GEN-LAST:event_btnCancelaVendaActionPerformed
    
    public void preencherTabelaCliente(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"ID","Nome"};
        conecta.conexao();
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {            
                dados.add(new Object[]{conecta.rs.getInt("id_clientes"),conecta.rs.getString("nome_clientes")});
        } while (conecta.rs.next());
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o array!!\n ERRO: "+ex);
        }
        
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tblPesquisa.setModel(modelo);
        tblPesquisa.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(0).setResizable(false);
        tblPesquisa.getColumnModel().getColumn(1).setPreferredWidth(590);
        tblPesquisa.getColumnModel().getColumn(1).setResizable(false);
        tblPesquisa.getTableHeader().setReorderingAllowed(false);
        tblPesquisa.setAutoResizeMode(tblPesquisa.AUTO_RESIZE_OFF);
        tblPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
       
    }
    
    public void preencherTabelaProduto(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"ID","Nome","Qtd"};
        conecta.conexao();
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {            
                dados.add(new Object[]{conecta.rs.getInt("id_produtos"),conecta.rs.getString("nome_produtos"),conecta.rs.getString("qtd_produtos")});
        } while (conecta.rs.next());
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o array!!\n ERRO: "+ex);
        }
        
        
        
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tblPesquisa.setModel(modelo);
        tblPesquisa.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(0).setResizable(false);
        tblPesquisa.getColumnModel().getColumn(1).setPreferredWidth(490);
        tblPesquisa.getColumnModel().getColumn(1).setResizable(false);
        tblPesquisa.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblPesquisa.getColumnModel().getColumn(2).setResizable(false);
        tblPesquisa.getTableHeader().setReorderingAllowed(false);
        tblPesquisa.setAutoResizeMode(tblPesquisa.AUTO_RESIZE_OFF);
        tblPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
       
    }
    
    public void preencherTabelaItens(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"Descrição","Quantidade","Valor Total"};
        conecta.conexao();
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {   
                float valorProduto = conecta.rs.getFloat("preco_produtos");
                int qtdVendida = Integer.parseInt(txtQtd.getText());
                dados.add(new Object[]{conecta.rs.getString("nome_produtos"),conecta.rs.getString("qtd_produtosvendas"), conecta.rs.getString("preco_produtos")});
        } while (conecta.rs.next());
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o AAAAAAAAAarray!!\n ERRO: "+ex);
        }
        
        
        
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tblItems.setModel(modelo);
        tblItems.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblItems.getColumnModel().getColumn(0).setResizable(false);
        tblItems.getColumnModel().getColumn(1).setPreferredWidth(490);
        tblItems.getColumnModel().getColumn(1).setResizable(false);
        tblItems.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblItems.getColumnModel().getColumn(2).setResizable(false);
        tblItems.getTableHeader().setReorderingAllowed(false);
        tblItems.setAutoResizeMode(tblItems.AUTO_RESIZE_OFF);
        tblItems.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        SomaProduto();
       
    }
    
    public void SomaProduto() {
        total = 0;
        int qtd=0;
        float valor=0;
        conecta.executaSQL("select * from itens_venda_produtos inner join produtos on itens_venda_produtos.id_produtos=produtos.id_produtos where id_vendas="+codVenda);
        try {
            //conecta.rs.first();
            while(conecta.rs.next()){
                qtd = conecta.rs.getInt("qtd_produtosvendas");
                valor = conecta.rs.getFloat(("preco_produtos"));
                total =  conecta.rs.getFloat("preco_produtos")* conecta.rs.getInt("qtd_produtosvendas");
                
                JOptionPane.showMessageDialog(null, "qtd "+qtd+"valor "+valor);
               
            }
            txtValorVendaTotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro na soma do total"+ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnBuscaProduto;
    private javax.swing.JButton btnCancelaVenda;
    private javax.swing.JButton btnMenuClientes;
    private javax.swing.JButton btnMenuEstoque;
    private javax.swing.JButton btnMenuFornecedores;
    private javax.swing.JButton btnMenuPedidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblPesquisa;
    private javax.swing.JFormattedTextField txtDataVenda;
    private javax.swing.JTextField txtNomeClienteVenda;
    private javax.swing.JTextField txtProdutoVenda;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtValorItemVenda;
    private javax.swing.JTextField txtValorVendaTotal;
    // End of variables declaration//GEN-END:variables
}
